# RL and ML parameters

neural_network: [256,256]  # Doubling the size of ANN
policyName: 'CustomPolicy' # Name of policy. This can be ignored.
gamma: 0.95                # Discount factor
n_steps: 1_000             # Number of steps to run in each environment per update. Batchsize = n_steps*n_env
ent_coef: 0.001            # Entropy coefficient
learning_rate:  0.001      # Learning Rate, can be a funcion
vf_coef: .1                # Value Function Coefficient in Loss Function
max_grad_norm: 0.5         # Clipping factor for gradients. Should prevent exploding gradients
lam: 0.95                  # Factor for bias vs variance for GAE
batch_size:  100           # Number of minibatches at each update.
noptepochs: 7              # Number of epochs each update
cliprange: 0.2             # Cliprange for PPO
seed: 12345                # Seed for neural network initialization
nEnvs: 4                   # Number of parallel environments

# Callback parameters
num_ep_save: 2    #  Calculate the mean reward for this number of episodes and save that model
check_freq: 50000 # After how many timesteps do we check the frequency

# TODO: Add pointer to callback here to instantiate it

# Post training parameters
test: True
num_tests: 3
render: True
time_per_test: 1000